# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-09 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('contact', models.IntegerField()),
                ('neighbourhood', models.CharField(max_length=60)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='profile/')),
            ],
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='occupants',
            field=models.IntegerField(),
        ),
    ]
